
image:
  file: .gitpod.Dockerfile

#vscode:
#  extensions:
#    - ms-python.python

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    main: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false

tasks:
  - name: Install Python dependencies
    command: |
      pip install black
      exit
  - name: My Gitpod
    command: |
      echo Welcome to my gitpod!
      echo "alias hello='echo hello world'" >> ~/.bashrc
      source ~/.bashrc

