
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    main: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false

tasks:
  - name: Pylint settings
    init: |
      cp /workspace/my-gitpod/.pylintrc ~/.pylintrc
      exit
  - name: VSCode settings
    command: |
      mkdir -p /workspace/my-gitpod/.vscode
      cat <<EOF > /workspace/my-gitpod/.vscode/settings.json
      {
        "python.defaultInterpreterPath": "python3",
        "python.linting.enabled": true,
        "python.linting.pylintEnabled": true,
        "python.linting.pylintArgs": [
          "--max-line-length=80"
        ],
        "[python]": {
          "editor.insertSpaces": true,
          "editor.tabSize": 4
        },
        "editor.formatOnSave": true,
        "editor.lineNumbers": "on",
        "python.formatting.provider": "black",
        "python.formatting.blackArgs": ["--line-length", "79"]
      }
      EOF
      exit
  - name: Install Python dependencies
    command: |
      pip install black
      exit
  - name: My Gitpod
    command: |
      echo Welcome to my gitpod!
      echo "alias hello='echo hello world'" >> ~/.bashrc
      source ~/.bashrc
