image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - HashiCorp.terraform
    - ms-python.python
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    main: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false

tasks:
  - name: Set up environment variables
    env: |
      MY_ENV_VAR=123
    command: |
      echo "alias hello='echo hello world'" >> ~/.bashrc
      source ~/.bashrc

